services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - backend
    restart: unless-stopped  # Better than 'always'

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:  